### PR TITLE
Convert build to Autotools, and fix a couple compiler warnings

### PR DESCRIPTION
**Pull request by greg-kennedy**
These commits will accomplish two things:
* Replace the pre-built Makefile with automake/autoconf build tools.  This should help with portability.  To build and install now, use:
`autoreconf -i`
`./configure`
`make`
`make install`
* Fix printf specifiers.  The correct form is `%zu` for `size_t`, which works on C99, GNU C, and Visual Studio as of 2015.  (Previous compilers should cast to `unsigned long` and use `%lu`)

### CODE REVIEW

**Comment by tomclegg** [comment]
Thanks! %z looks good but the autoconf stuff feels heavy -- is there a particular portability issue this fixes?

**Comment by greg-kennedy** [comment]
Not really... I just like autotools :stuck_out_tongue: 

But actually I have seen some package maintainers say they like autotools builds because they're predictable.

**Comment by tomclegg** [comment]
OK. I'd rather keep it simple. I hope you don't mind if I take the printfs but leave out the autotools.

**Comment by tomclegg** [comment]
Cherry-picked the printf fixes (thanks again). Also rewrote history to fix email addresses in some recent commits, which has confused github, whoops.

**Pull request closed without merging**
